// This file will be auto-generated by Supabase CLI
// Run: supabase gen types typescript --local > lib/supabase/types.ts

export type user_role = 'admin' | 'staff' | 'client';
export type case_status = 'draft' | 'sent' | 'in_progress' | 'paid' | 'closed';
export type case_event_type = 
  | 'created'
  | 'email_sent'
  | 'status_changed'
  | 'note_added'
  | 'payment_marked'
  | 'attachment_added'
  | 'otp_failed'
  | 'otp_verified';
export type task_status = 'open' | 'done';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          role: user_role;
          full_name: string | null;
          phone: string | null;
          organization_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          role?: user_role;
          full_name?: string | null;
          phone?: string | null;
          organization_id?: string | null;
        };
        Update: {
          id?: string;
          role?: user_role;
          full_name?: string | null;
          phone?: string | null;
          organization_id?: string | null;
        };
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          vat_number: string | null;
          address_street: string | null;
          address_city: string | null;
          address_postal_code: string | null;
          address_country: string;
          billing_email: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          vat_number?: string | null;
          address_street?: string | null;
          address_city?: string | null;
          address_postal_code?: string | null;
          address_country?: string;
          billing_email: string;
        };
        Update: {
          name?: string;
          vat_number?: string | null;
          address_street?: string | null;
          address_city?: string | null;
          address_postal_code?: string | null;
          address_country?: string;
          billing_email?: string;
        };
      };
      debtors: {
        Row: {
          id: string;
          name: string | null;
          company_name: string | null;
          email: string;
          address_street: string | null;
          address_city: string | null;
          address_postal_code: string | null;
          address_country: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name?: string | null;
          company_name?: string | null;
          email: string;
          address_street?: string | null;
          address_city?: string | null;
          address_postal_code?: string | null;
          address_country?: string;
        };
        Update: {
          name?: string | null;
          company_name?: string | null;
          email?: string;
          address_street?: string | null;
          address_city?: string | null;
          address_postal_code?: string | null;
          address_country?: string;
        };
      };
      cases: {
        Row: {
          id: string;
          organization_id: string;
          debtor_id: string;
          created_by: string;
          status: case_status;
          principal_amount: number;
          additional_costs: number;
          total_amount: number;
          currency: string;
          structured_reference: string | null;
          invoice_number: string | null;
          invoice_date: string | null;
          due_date: string | null;
          last_activity_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          debtor_id: string;
          created_by: string;
          status?: case_status;
          principal_amount: number;
          additional_costs?: number;
          total_amount: number;
          currency?: string;
          structured_reference?: string | null;
          invoice_number?: string | null;
          invoice_date?: string | null;
          due_date?: string | null;
        };
        Update: {
          status?: case_status;
          principal_amount?: number;
          additional_costs?: number;
          total_amount?: number;
          structured_reference?: string | null;
          invoice_number?: string | null;
          invoice_date?: string | null;
          due_date?: string | null;
        };
      };
      case_events: {
        Row: {
          id: string;
          case_id: string;
          actor_profile_id: string | null;
          type: case_event_type;
          message: string;
          metadata: Record<string, any>;
          created_at: string;
        };
        Insert: {
          id?: string;
          case_id: string;
          actor_profile_id?: string | null;
          type: case_event_type;
          message: string;
          metadata?: Record<string, any>;
        };
        Update: {
          message?: string;
          metadata?: Record<string, any>;
        };
      };
    };
  };
}

